version: '3.8'
services:
    webapp:
        build: .
        ports:
            - "80:8000"
        volumes:
            - .:/django_base
        depends_on:
            - postgresql
    postgresql:
        image: postgis/postgis
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - pg_data:/var/lib/postgresql/data
    selenium:
        image: selenium/standalone-chrome
volumes:
    pg_data:
